# Tomcat
server:
  port: 8082

#spring
spring:
  datasource:
    username: root
    password: FYADXZ@002
    url: jdbc:mysql://localhost:3306/mgt_tpl?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mgt.plat.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ASSIGN_ID:"", ASSIGN_UUID:"", NONE:"";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
      #刷新mapper 调试神器
    refresh: true
# 原生配置
configuration:
  map-underscore-to-camel-case: true
  cache-enabled: false